spring:
  server:
    port: 8888
#  application:
#    name=train:
  datasource:
    url: jdbc:mysql://localhost:3306/train?useSSL=false&serverTimezone=UTC
    username: root
    password:  "" # Mật khẩu trống""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true