spring:
  security:
    user:
      name: user
      password: password
  redis:
    host:  localhost

    port: 6379
    password:
  application:
    name: train
  datasource:

#    host.docker.internal
#    url: jdbc:mysql://localhost:3306/db_train_ticket_system?useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/train_ticket_system?useSSL=false&serverTimezone=UTC
# =======

# #    host.docker.internal
# #    url: jdbc:mysql://localhost:3306/db_train_ticket_system?useSSL=false&serverTimezone=UTC
#     url: jdbc:mysql://localhost:3306/train_ticket_system?useSSL=false&serverTimezone=UTC
# #    url: jdbc:mysql://host.docker.internal:3306/train_ticket_system?useSSL=false&serverTimezone=UTC
# >>>>>>> main
    url: jdbc:mysql://localhost:3306/train_ticket_system?useSSL=false&serverTimezone=UTC
    username: hoang
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hoang290603@gmail.com
    password: xjwqbmultpylqigd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: 10000
  refresh-expiration: 86400
  secretKey: "bXlfc3VwZXJfc2VjdXJlX3NlY3JldF9rZXlfZm9yX3RhdWhvYV8xMjM0NTY3ODkwIQ=="

logging:
  level:
    root: warn
